from __future__ import annotations

import json
from datetime import date, datetime, timedelta, timezone
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
JOBS_DIR = REPO_ROOT / "data" / "jobs"
DOCS_DIR = REPO_ROOT / "docs" / "content-calendars"

CALENDAR_LABEL = "2026-05-to-06"
START_DATE = date(2026, 5, 20)
CREATED_AT = "2026-05-19T18:00:00+04:00"
UPDATED_AT = "2026-05-19T18:00:00+04:00"
REVIEWER = "seo-expert"


def slugify(value: str) -> str:
    cleaned = [
        char.lower() if char.isalnum() else "-"
        for char in str(value).strip()
    ]
    slug = "".join(cleaned)
    while "--" in slug:
        slug = slug.replace("--", "-")
    return slug.strip("-")


def next_workdays(start: date, count: int) -> list[str]:
    dates: list[str] = []
    current = start
    while len(dates) < count:
        if current.weekday() < 5:
            dates.append(current.isoformat())
        current += timedelta(days=1)
    return dates

CRANES = [
    {
        "date": "2026-06-01",
        "job_id": "2026-05-19-cranes-auctions-buy-used-crane-at-auction",
        "topic": "How to buy a used crane at auction",
        "primary_keyword": "how to buy a used crane at auction",
        "secondary_keywords": [
            "used crane auction buyer checklist",
            "buy used crane online",
            "crane bidding tips",
            "heavy equipment auction checklist",
        ],
        "category_slug": "buying-guides",
        "category_name": "Buying Guides",
        "cluster": "buyer acquisition",
        "lead_goal": "buyer leads",
        "score": 88,
        "priority": "high",
        "word_count": 1800,
        "rationale": "Strong buyer-intent query with clear auction relevance and good internal-linking value across inspection, bidding, and logistics topics.",
        "tags": ["used crane buying", "auction buyer checklist", "inspection prep", "bidding strategy"],
        "links": ["auction landing pages", "equipment category pages", "contact pages"],
    },
    {
        "date": "2026-06-02",
        "job_id": "2026-05-19-cranes-auctions-used-crane-inspection-checklist",
        "topic": "Used crane inspection checklist before you bid",
        "primary_keyword": "used crane inspection checklist",
        "secondary_keywords": [
            "crane condition checklist",
            "inspect crane before auction",
            "used crane due diligence",
            "heavy equipment inspection list",
        ],
        "category_slug": "equipment-insights",
        "category_name": "Equipment Insights",
        "cluster": "buyer acquisition",
        "lead_goal": "buyer leads",
        "score": 86,
        "priority": "high",
        "word_count": 1800,
        "rationale": "Checklist format is easy to differentiate, supports buyer trust, and creates strong cluster leverage for crane buying and auction due diligence.",
        "tags": ["inspection checklist", "used crane condition", "auction prep", "buyer diligence"],
        "links": ["buying guide posts", "auction landing pages", "contact pages"],
    },
    {
        "date": "2026-06-03",
        "job_id": "2026-05-19-cranes-auctions-how-to-value-used-crane",
        "topic": "How to value a used crane before selling",
        "primary_keyword": "how to value a used crane",
        "secondary_keywords": [
            "used crane value",
            "crane appraisal factors",
            "equipment valuation checklist",
            "what affects crane resale value",
        ],
        "category_slug": "equipment-insights",
        "category_name": "Equipment Insights",
        "cluster": "seller acquisition",
        "lead_goal": "seller leads",
        "score": 82,
        "priority": "high",
        "word_count": 1700,
        "rationale": "High seller usefulness and good pre-listing fit, but slightly harder than more explicit transaction-adjacent auction topics.",
        "tags": ["equipment valuation", "used crane pricing", "resale factors", "appraisal prep"],
        "links": ["selling guide posts", "contact pages", "market updates"],
    },
    {
        "date": "2026-06-04",
        "job_id": "2026-05-19-cranes-auctions-auction-vs-private-sale-heavy-equipment",
        "topic": "Auction vs private sale for heavy equipment",
        "primary_keyword": "auction vs private sale heavy equipment",
        "secondary_keywords": [
            "sell heavy equipment at auction",
            "private sale vs auction equipment",
            "equipment resale strategy",
            "when to use an auction",
        ],
        "category_slug": "auction-strategy",
        "category_name": "Auction Strategy",
        "cluster": "seller acquisition",
        "lead_goal": "seller leads",
        "score": 80,
        "priority": "medium",
        "word_count": 1600,
        "rationale": "Useful decision-stage topic with good commercial relevance, though slightly broader and less direct than seller workflow and checklist queries.",
        "tags": ["auction strategy", "private sale comparison", "seller decision", "equipment resale"],
        "links": ["selling guide posts", "auction landing pages", "contact pages"],
    },
    {
        "date": "2026-06-05",
        "job_id": "2026-06-05-cranes-auctions-crane-transport-logistics-after-auction",
        "topic": "Crane transport logistics after auction",
        "primary_keyword": "crane transport logistics after auction",
        "secondary_keywords": [
            "move crane after auction",
            "heavy equipment transport after sale",
            "crane pickup logistics",
            "auction removal planning",
        ],
        "category_slug": "transport-logistics",
        "category_name": "Transport & Logistics",
        "cluster": "buyer fulfillment",
        "lead_goal": "buyer leads",
        "score": 78,
        "priority": "medium",
        "word_count": 1600,
        "rationale": "Operational topic with strong post-sale relevance that can convert cautious buyers who need clarity on removal and freight planning.",
        "tags": ["transport logistics", "auction removal", "crane shipping", "post-sale planning"],
        "links": ["auction landing pages", "contact pages", "equipment category pages"],
    },
    {
        "date": "2026-06-08",
        "job_id": "2026-06-08-cranes-auctions-best-time-to-sell-used-crane",
        "topic": "Best time to sell a used crane",
        "primary_keyword": "best time to sell a used crane",
        "secondary_keywords": [
            "when to sell used crane",
            "crane market timing",
            "heavy equipment resale season",
            "sell crane at best price",
        ],
        "category_slug": "market-updates",
        "category_name": "Market Updates",
        "cluster": "seller acquisition",
        "lead_goal": "seller leads",
        "score": 84,
        "priority": "high",
        "word_count": 1700,
        "rationale": "Strong seller-timing topic that can pull valuation and listing inquiries from owners who are already thinking about market readiness.",
        "tags": ["market timing", "seller strategy", "used crane market", "resale timing"],
        "links": ["selling guide posts", "contact pages", "auction landing pages"],
    },
    {
        "date": "2026-06-09",
        "job_id": "2026-06-09-cranes-auctions-documents-needed-to-sell-crane-at-auction",
        "topic": "Documents needed to sell a crane at auction",
        "primary_keyword": "documents needed to sell a crane at auction",
        "secondary_keywords": [
            "crane title paperwork",
            "auction seller documents",
            "equipment ownership records",
            "paperwork for selling crane",
        ],
        "category_slug": "selling-guides",
        "category_name": "Selling Guides",
        "cluster": "seller acquisition",
        "lead_goal": "seller leads",
        "score": 87,
        "priority": "high",
        "word_count": 1700,
        "rationale": "High-conversion seller topic because paperwork readiness is a real blocker that often surfaces right before a listing inquiry.",
        "tags": ["seller paperwork", "auction documents", "ownership records", "listing prep"],
        "links": ["contact pages", "auction landing pages", "selling guide posts"],
    },
    {
        "date": "2026-06-10",
        "job_id": "2026-06-10-cranes-auctions-what-affects-used-crane-resale-value",
        "topic": "What affects used crane resale value",
        "primary_keyword": "what affects used crane resale value",
        "secondary_keywords": [
            "crane resale factors",
            "used crane pricing factors",
            "equipment depreciation crane",
            "crane value checklist",
        ],
        "category_slug": "equipment-insights",
        "category_name": "Equipment Insights",
        "cluster": "seller acquisition",
        "lead_goal": "seller leads",
        "score": 83,
        "priority": "high",
        "word_count": 1700,
        "rationale": "Practical valuation content that supports lead capture from owners still deciding whether to sell now or improve the asset first.",
        "tags": ["resale value", "pricing factors", "equipment depreciation", "seller prep"],
        "links": ["selling guide posts", "contact pages", "market updates"],
    },
    {
        "date": "2026-06-11",
        "job_id": "2026-06-11-cranes-auctions-rough-terrain-crane-buyer-checklist",
        "topic": "Rough terrain crane buyer checklist",
        "primary_keyword": "rough terrain crane buyer checklist",
        "secondary_keywords": [
            "buy rough terrain crane",
            "rough terrain crane inspection",
            "used RT crane checklist",
            "auction crane buyer tips",
        ],
        "category_slug": "buying-guides",
        "category_name": "Buying Guides",
        "cluster": "buyer acquisition",
        "lead_goal": "buyer leads",
        "score": 81,
        "priority": "medium",
        "word_count": 1700,
        "rationale": "Specific equipment-class checklist content can win earlier than broad head terms and attract serious buyer conversations.",
        "tags": ["rough terrain crane", "buyer checklist", "inspection prep", "used crane buying"],
        "links": ["equipment category pages", "auction landing pages", "contact pages"],
    },
    {
        "date": "2026-06-12",
        "job_id": "2026-06-12-cranes-auctions-crawler-crane-buyer-checklist",
        "topic": "Crawler crane buyer checklist",
        "primary_keyword": "crawler crane buyer checklist",
        "secondary_keywords": [
            "buy crawler crane",
            "crawler crane inspection",
            "used crawler crane tips",
            "crawler crane auction guide",
        ],
        "category_slug": "buying-guides",
        "category_name": "Buying Guides",
        "cluster": "buyer acquisition",
        "lead_goal": "buyer leads",
        "score": 81,
        "priority": "medium",
        "word_count": 1700,
        "rationale": "Narrow buyer-intent content helps build authority in crane subcategories while staying commercially useful.",
        "tags": ["crawler crane", "buyer checklist", "auction guide", "inspection prep"],
        "links": ["equipment category pages", "auction landing pages", "contact pages"],
    },
    {
        "date": "2026-06-15",
        "job_id": "2026-06-15-cranes-auctions-mobile-crane-inspection-checklist",
        "topic": "Mobile crane inspection checklist before buying",
        "primary_keyword": "mobile crane inspection checklist",
        "secondary_keywords": [
            "inspect mobile crane before buying",
            "mobile crane auction checklist",
            "used mobile crane condition",
            "buyer due diligence mobile crane",
        ],
        "category_slug": "equipment-insights",
        "category_name": "Equipment Insights",
        "cluster": "buyer acquisition",
        "lead_goal": "buyer leads",
        "score": 80,
        "priority": "medium",
        "word_count": 1700,
        "rationale": "Inspection content is highly actionable and supports serious buyers who are closest to making a purchase decision.",
        "tags": ["mobile crane", "inspection checklist", "buyer due diligence", "auction prep"],
        "links": ["buying guide posts", "equipment category pages", "contact pages"],
    },
    {
        "date": "2026-06-16",
        "job_id": "2026-06-16-cranes-auctions-how-reserve-prices-work-equipment-auctions",
        "topic": "How reserve prices work at equipment auctions",
        "primary_keyword": "how reserve prices work at equipment auctions",
        "secondary_keywords": [
            "auction reserve price equipment",
            "seller reserve strategy",
            "equipment auction minimum price",
            "reserve price explained",
        ],
        "category_slug": "auction-strategy",
        "category_name": "Auction Strategy",
        "cluster": "seller acquisition",
        "lead_goal": "seller leads",
        "score": 79,
        "priority": "medium",
        "word_count": 1600,
        "rationale": "Seller education topic with strong consultative value that can lead directly into valuation and listing conversations.",
        "tags": ["reserve strategy", "auction pricing", "seller education", "auction terms"],
        "links": ["selling guide posts", "contact pages", "auction landing pages"],
    },
    {
        "date": "2026-06-17",
        "job_id": "2026-06-17-cranes-auctions-compare-used-crane-auction-listings",
        "topic": "How to compare used crane auction listings",
        "primary_keyword": "compare used crane auction listings",
        "secondary_keywords": [
            "evaluate crane listings",
            "used crane listing comparison",
            "auction listing buyer guide",
            "compare crane specs online",
        ],
        "category_slug": "buying-guides",
        "category_name": "Buying Guides",
        "cluster": "buyer acquisition",
        "lead_goal": "buyer leads",
        "score": 77,
        "priority": "medium",
        "word_count": 1600,
        "rationale": "Comparison intent supports high-quality buyer traffic and naturally points users toward contact or marketplace assistance.",
        "tags": ["listing comparison", "buyer guide", "auction research", "crane specs"],
        "links": ["auction landing pages", "equipment category pages", "contact pages"],
    },
    {
        "date": "2026-06-18",
        "job_id": "2026-06-18-cranes-auctions-common-mistakes-buying-heavy-equipment-at-auction",
        "topic": "Common mistakes when buying heavy equipment at auction",
        "primary_keyword": "common mistakes buying heavy equipment at auction",
        "secondary_keywords": [
            "auction buying mistakes",
            "used equipment auction tips",
            "avoid auction bidding mistakes",
            "heavy equipment buyer guide",
        ],
        "category_slug": "buying-guides",
        "category_name": "Buying Guides",
        "cluster": "buyer acquisition",
        "lead_goal": "buyer leads",
        "score": 78,
        "priority": "medium",
        "word_count": 1600,
        "rationale": "Pain-point content performs well for early trust building and gives buyers a reason to engage before bidding.",
        "tags": ["auction mistakes", "buyer education", "heavy equipment tips", "bidding strategy"],
        "links": ["buying guide posts", "auction landing pages", "contact pages"],
    },
    {
        "date": "2026-06-19",
        "job_id": "2026-06-19-cranes-auctions-crane-title-and-lien-checklist-before-auction",
        "topic": "Crane title and lien checklist before auction",
        "primary_keyword": "crane title and lien checklist before auction",
        "secondary_keywords": [
            "crane lien paperwork",
            "title checklist before selling crane",
            "auction title issues crane",
            "ownership verification crane",
        ],
        "category_slug": "selling-guides",
        "category_name": "Selling Guides",
        "cluster": "seller acquisition",
        "lead_goal": "seller leads",
        "score": 82,
        "priority": "high",
        "word_count": 1600,
        "rationale": "Title and lien issues often block listings, making this a high-intent problem-solution topic for motivated sellers.",
        "tags": ["title checklist", "lien issues", "seller paperwork", "auction prep"],
        "links": ["contact pages", "selling guide posts", "auction landing pages"],
    },
    {
        "date": "2026-06-22",
        "job_id": "2026-06-22-cranes-auctions-how-to-choose-auction-partner-heavy-equipment",
        "topic": "How to choose an auction partner for heavy equipment",
        "primary_keyword": "how to choose an auction partner for heavy equipment",
        "secondary_keywords": [
            "best auction partner heavy equipment",
            "choose equipment auction company",
            "auction partner checklist",
            "heavy equipment seller support",
        ],
        "category_slug": "selling-guides",
        "category_name": "Selling Guides",
        "cluster": "seller acquisition",
        "lead_goal": "seller leads",
        "score": 85,
        "priority": "high",
        "word_count": 1700,
        "rationale": "This is a direct lead-generation topic because the searcher is evaluating who to trust with a sale, not just reading casually.",
        "tags": ["auction partner", "seller support", "lead generation", "auction checklist"],
        "links": ["contact pages", "auction landing pages", "selling guide posts"],
    },
    {
        "date": "2026-06-23",
        "job_id": "2026-06-23-cranes-auctions-how-to-prepare-crane-photos-for-sale-listing",
        "topic": "How to prepare crane photos for a sale listing",
        "primary_keyword": "how to prepare crane photos for a sale listing",
        "secondary_keywords": [
            "crane listing photos",
            "heavy equipment photo checklist",
            "auction photo prep crane",
            "sell crane with better photos",
        ],
        "category_slug": "selling-guides",
        "category_name": "Selling Guides",
        "cluster": "seller acquisition",
        "lead_goal": "seller leads",
        "score": 76,
        "priority": "medium",
        "word_count": 1500,
        "rationale": "Visual-prep content supports sellers who are close to listing and can move them toward a guided intake conversation.",
        "tags": ["listing photos", "seller prep", "auction photography", "conversion support"],
        "links": ["selling guide posts", "contact pages", "auction landing pages"],
    },
    {
        "date": "2026-06-24",
        "job_id": "2026-06-24-cranes-auctions-what-to-ask-before-bidding-on-used-crane",
        "topic": "What to ask before bidding on a used crane",
        "primary_keyword": "what to ask before bidding on a used crane",
        "secondary_keywords": [
            "questions before bidding on crane",
            "used crane auction questions",
            "crane bidding checklist",
            "buyer diligence crane",
        ],
        "category_slug": "buying-guides",
        "category_name": "Buying Guides",
        "cluster": "buyer acquisition",
        "lead_goal": "buyer leads",
        "score": 79,
        "priority": "medium",
        "word_count": 1600,
        "rationale": "Question-driven content closely matches buyer behavior and gives the site a natural way to offer expert guidance.",
        "tags": ["buyer questions", "bidding checklist", "auction prep", "crane due diligence"],
        "links": ["auction landing pages", "equipment category pages", "contact pages"],
    },
    {
        "date": "2026-06-25",
        "job_id": "2026-06-25-cranes-auctions-sell-multiple-fleet-cranes-through-one-auction-plan",
        "topic": "How to sell multiple fleet cranes through one auction plan",
        "primary_keyword": "sell multiple fleet cranes through one auction plan",
        "secondary_keywords": [
            "fleet crane liquidation",
            "sell multiple cranes auction",
            "fleet equipment auction plan",
            "bulk crane sale strategy",
        ],
        "category_slug": "selling-guides",
        "category_name": "Selling Guides",
        "cluster": "seller acquisition",
        "lead_goal": "seller leads",
        "score": 81,
        "priority": "medium",
        "word_count": 1700,
        "rationale": "Fleet-focused content aligns with high-value commercial sellers and can produce fewer but much stronger leads.",
        "tags": ["fleet sales", "bulk auction", "seller strategy", "fleet disposal"],
        "links": ["contact pages", "auction landing pages", "selling guide posts"],
    },
    {
        "date": "2026-06-26",
        "job_id": "2026-06-26-cranes-auctions-when-to-repair-vs-sell-used-crane",
        "topic": "When to repair vs sell a used crane",
        "primary_keyword": "when to repair vs sell a used crane",
        "secondary_keywords": [
            "repair or sell crane",
            "used crane resale decision",
            "equipment repair vs auction",
            "crane lifecycle decision",
        ],
        "category_slug": "equipment-insights",
        "category_name": "Equipment Insights",
        "cluster": "seller acquisition",
        "lead_goal": "seller leads",
        "score": 75,
        "priority": "medium",
        "word_count": 1600,
        "rationale": "Decision-stage owner content can qualify sellers who need guidance before they commit to listing.",
        "tags": ["repair vs sell", "resale decision", "owner guide", "equipment lifecycle"],
        "links": ["selling guide posts", "contact pages", "market updates"],
    },
    {
        "date": "2026-06-29",
        "job_id": "2026-06-29-cranes-auctions-how-buyers-evaluate-crane-condition-reports",
        "topic": "How heavy equipment buyers evaluate crane condition reports",
        "primary_keyword": "how buyers evaluate crane condition reports",
        "secondary_keywords": [
            "crane condition report guide",
            "used crane inspection report",
            "buyer review condition report",
            "heavy equipment report checklist",
        ],
        "category_slug": "equipment-insights",
        "category_name": "Equipment Insights",
        "cluster": "buyer acquisition",
        "lead_goal": "buyer leads",
        "score": 74,
        "priority": "medium",
        "word_count": 1600,
        "rationale": "A strong trust-building topic that helps serious buyers interpret condition data and lean toward guided buying support.",
        "tags": ["condition reports", "buyer review", "inspection guide", "equipment diligence"],
        "links": ["buying guide posts", "auction landing pages", "contact pages"],
    },
    {
        "date": "2026-06-30",
        "job_id": "2026-06-30-cranes-auctions-financing-questions-buyers-ask-at-crane-auctions",
        "topic": "Financing questions buyers ask at crane auctions",
        "primary_keyword": "financing questions buyers ask at crane auctions",
        "secondary_keywords": [
            "crane auction financing",
            "used crane funding questions",
            "buyer financing checklist auction",
            "heavy equipment finance questions",
        ],
        "category_slug": "buying-guides",
        "category_name": "Buying Guides",
        "cluster": "buyer acquisition",
        "lead_goal": "buyer leads",
        "score": 72,
        "priority": "medium",
        "word_count": 1500,
        "rationale": "Lower-volume but high-friction topic that can surface buyer concerns early and move them toward direct contact.",
        "tags": ["auction financing", "buyer questions", "funding checklist", "equipment finance"],
        "links": ["auction landing pages", "contact pages", "buying guide posts"],
    },
]

JMA = [
    {
        "date": "2026-06-01",
        "job_id": "2026-05-19-jma-golfcarts-sell-used-golf-cart-online",
        "topic": "How to sell a used golf cart online",
        "primary_keyword": "sell used golf cart online",
        "secondary_keywords": [
            "used golf cart marketplace",
            "sell golf cart fast",
            "golf cart resale checklist",
            "list golf cart for sale",
        ],
        "category_slug": "selling-guides",
        "category_name": "Selling Guides",
        "cluster": "seller acquisition",
        "lead_goal": "seller leads",
        "score": 92,
        "priority": "high",
        "word_count": 1700,
        "rationale": "Very strong marketplace fit with clear seller intent, practical content structure, and high value as an early trust-building entry point for a new site.",
        "tags": ["used golf cart sales", "golf cart resale process", "seller checklist", "online marketplace tips"],
        "links": ["inventory and auction listing pages", "contact and lead capture sections", "brand and category landing pages"],
    },
    {
        "date": "2026-06-02",
        "job_id": "2026-05-19-jma-golfcarts-what-to-look-for-buying-used-golf-cart",
        "topic": "What to look for when buying a used golf cart",
        "primary_keyword": "what to look for when buying a used golf cart",
        "secondary_keywords": [
            "used golf cart buying checklist",
            "inspect golf cart before buying",
            "buy used golf cart online",
            "used golf cart buyer guide",
        ],
        "category_slug": "buying-guides",
        "category_name": "Buying Guides",
        "cluster": "buyer acquisition",
        "lead_goal": "buyer leads",
        "score": 90,
        "priority": "high",
        "word_count": 1700,
        "rationale": "Excellent new-site target because it matches buyer research behavior, supports comparison content, and is easy to make genuinely helpful.",
        "tags": ["used golf cart buying", "inspection checklist", "buyer guide", "marketplace tips"],
        "links": ["inventory and auction listing pages", "brand comparison posts", "contact sections"],
    },
    {
        "date": "2026-06-03",
        "job_id": "2026-05-19-jma-golfcarts-club-car-vs-ez-go-golf-cart",
        "topic": "Club Car vs EZGO golf cart",
        "primary_keyword": "club car vs ez go golf cart",
        "secondary_keywords": [
            "club car vs ezgo comparison",
            "best golf cart brand",
            "used club car vs ezgo",
            "golf cart brand comparison",
        ],
        "category_slug": "brand-comparisons",
        "category_name": "Brand Comparisons",
        "cluster": "buyer acquisition",
        "lead_goal": "buyer leads",
        "score": 84,
        "priority": "medium",
        "word_count": 1600,
        "rationale": "Brand comparison content can capture strong decision-stage traffic and support conversions, but requires clearer differentiation to outperform existing comparison pages.",
        "tags": ["brand comparison", "club car", "ezgo", "buyer guide"],
        "links": ["buying guide posts", "inventory pages", "contact sections"],
    },
    {
        "date": "2026-06-04",
        "job_id": "2026-05-19-jma-golfcarts-golf-cart-battery-replacement-cost",
        "topic": "Golf cart battery replacement cost",
        "primary_keyword": "golf cart battery replacement cost",
        "secondary_keywords": [
            "replace golf cart batteries",
            "electric golf cart battery cost",
            "golf cart ownership cost",
            "battery life golf cart",
        ],
        "category_slug": "maintenance-ownership",
        "category_name": "Maintenance & Ownership",
        "cluster": "ownership education",
        "lead_goal": "buyer leads",
        "score": 83,
        "priority": "medium",
        "word_count": 1600,
        "rationale": "Strong practical demand signal and helpfulness potential, with good top-of-funnel reach that can support later buyer-conversion content.",
        "tags": ["battery cost", "ownership guide", "electric golf cart maintenance", "replacement timing"],
        "links": ["buying guide posts", "inventory pages", "brand comparison posts"],
    },
    {
        "date": "2026-06-05",
        "job_id": "2026-05-19-jma-golfcarts-best-utility-golf-carts",
        "topic": "Best utility golf carts for work and property use",
        "primary_keyword": "best utility golf carts",
        "secondary_keywords": [
            "utility golf carts for sale",
            "golf carts for work use",
            "commercial golf cart buying guide",
            "property maintenance golf cart",
        ],
        "category_slug": "utility-work-carts",
        "category_name": "Utility & Work Carts",
        "cluster": "buyer acquisition",
        "lead_goal": "buyer leads",
        "score": 79,
        "priority": "medium",
        "word_count": 1600,
        "rationale": "Commercially useful and category-building, but broader and potentially more competitive than the highest-priority long-tail buyer and seller topics.",
        "tags": ["utility carts", "work carts", "commercial buying guide", "property use"],
        "links": ["inventory and auction listing pages", "contact sections", "maintenance posts"],
    },
    {
        "date": "2026-06-08",
        "job_id": "2026-06-08-jma-golfcarts-how-to-price-used-golf-cart-for-sale",
        "topic": "How to price a used golf cart for sale",
        "primary_keyword": "how to price a used golf cart for sale",
        "secondary_keywords": [
            "used golf cart pricing",
            "golf cart resale value",
            "how much is my golf cart worth",
            "price golf cart to sell",
        ],
        "category_slug": "selling-guides",
        "category_name": "Selling Guides",
        "cluster": "seller acquisition",
        "lead_goal": "seller leads",
        "score": 88,
        "priority": "high",
        "word_count": 1700,
        "rationale": "Seller-intent topic with strong commercial fit because pricing uncertainty often appears right before a listing inquiry.",
        "tags": ["used golf cart pricing", "seller guide", "resale value", "listing prep"],
        "links": ["contact sections", "inventory pages", "selling guide posts"],
    },
    {
        "date": "2026-06-09",
        "job_id": "2026-06-09-jma-golfcarts-best-golf-cart-for-neighborhood-use",
        "topic": "Best golf cart for neighborhood use",
        "primary_keyword": "best golf cart for neighborhood use",
        "secondary_keywords": [
            "neighborhood golf cart guide",
            "best golf cart for personal use",
            "residential golf cart buying guide",
            "golf cart for community use",
        ],
        "category_slug": "buying-guides",
        "category_name": "Buying Guides",
        "cluster": "buyer acquisition",
        "lead_goal": "buyer leads",
        "score": 85,
        "priority": "high",
        "word_count": 1600,
        "rationale": "High-intent use-case content can convert buyers earlier than broad brand pages because it starts with the real ownership context.",
        "tags": ["neighborhood carts", "personal use", "buyer guide", "residential carts"],
        "links": ["inventory pages", "street legal posts", "contact sections"],
    },
    {
        "date": "2026-06-10",
        "job_id": "2026-06-10-jma-golfcarts-best-golf-cart-for-campground-or-resort-use",
        "topic": "Best golf cart for campground or resort use",
        "primary_keyword": "best golf cart for campground or resort use",
        "secondary_keywords": [
            "resort golf cart guide",
            "campground golf cart options",
            "fleet golf cart buyer guide",
            "golf cart for hospitality use",
        ],
        "category_slug": "utility-work-carts",
        "category_name": "Utility & Work Carts",
        "cluster": "buyer acquisition",
        "lead_goal": "buyer leads",
        "score": 82,
        "priority": "high",
        "word_count": 1600,
        "rationale": "Use-case led commercial content helps capture higher-value fleet and hospitality buyers who want consultative guidance.",
        "tags": ["resort carts", "campground use", "fleet guide", "hospitality carts"],
        "links": ["inventory pages", "contact sections", "utility cart posts"],
    },
    {
        "date": "2026-06-11",
        "job_id": "2026-06-11-jma-golfcarts-used-golf-cart-inspection-checklist-before-buying",
        "topic": "Used golf cart inspection checklist before buying",
        "primary_keyword": "used golf cart inspection checklist",
        "secondary_keywords": [
            "inspect used golf cart",
            "golf cart buyer checklist",
            "used golf cart condition check",
            "golf cart auction checklist",
        ],
        "category_slug": "buying-guides",
        "category_name": "Buying Guides",
        "cluster": "buyer acquisition",
        "lead_goal": "buyer leads",
        "score": 87,
        "priority": "high",
        "word_count": 1700,
        "rationale": "Checklist-style buyer content is highly skimmable, trustworthy, and likely to produce qualified lead conversations.",
        "tags": ["inspection checklist", "buyer guide", "used golf cart condition", "marketplace prep"],
        "links": ["inventory pages", "brand comparison posts", "contact sections"],
    },
    {
        "date": "2026-06-12",
        "job_id": "2026-06-12-jma-golfcarts-how-long-do-golf-cart-batteries-last",
        "topic": "How long do golf cart batteries last?",
        "primary_keyword": "how long do golf cart batteries last",
        "secondary_keywords": [
            "golf cart battery lifespan",
            "battery age used golf cart",
            "electric golf cart ownership",
            "battery replacement timing",
        ],
        "category_slug": "maintenance-ownership",
        "category_name": "Maintenance & Ownership",
        "cluster": "ownership education",
        "lead_goal": "buyer leads",
        "score": 80,
        "priority": "medium",
        "word_count": 1500,
        "rationale": "Practical ownership questions generate broad interest and help buyers qualify whether a listing is worth pursuing.",
        "tags": ["battery lifespan", "ownership guide", "electric carts", "maintenance timing"],
        "links": ["buying guide posts", "inventory pages", "contact sections"],
    },
    {
        "date": "2026-06-15",
        "job_id": "2026-06-15-jma-golfcarts-street-legal-golf-cart-requirements-buyer-checklist",
        "topic": "Street legal golf cart requirements buyer checklist",
        "primary_keyword": "street legal golf cart requirements buyer checklist",
        "secondary_keywords": [
            "street legal golf cart checklist",
            "LSV golf cart requirements",
            "buy street legal golf cart",
            "road legal golf cart guide",
        ],
        "category_slug": "street-legal-carts",
        "category_name": "Street Legal Carts",
        "cluster": "buyer acquisition",
        "lead_goal": "buyer leads",
        "score": 84,
        "priority": "high",
        "word_count": 1700,
        "rationale": "Compliance-oriented content attracts serious buyers with clear intent and supports high-value consultation opportunities.",
        "tags": ["street legal", "buyer checklist", "LSV guide", "road-ready carts"],
        "links": ["inventory pages", "contact sections", "buying guide posts"],
    },
    {
        "date": "2026-06-16",
        "job_id": "2026-06-16-jma-golfcarts-how-to-take-better-photos-when-selling-golf-cart",
        "topic": "How to take better photos when selling a golf cart",
        "primary_keyword": "how to take better photos when selling a golf cart",
        "secondary_keywords": [
            "golf cart listing photos",
            "sell golf cart with better photos",
            "online listing photo checklist",
            "golf cart resale pictures",
        ],
        "category_slug": "selling-guides",
        "category_name": "Selling Guides",
        "cluster": "seller acquisition",
        "lead_goal": "seller leads",
        "score": 77,
        "priority": "medium",
        "word_count": 1500,
        "rationale": "A practical conversion-assist topic that helps sellers feel supported and closer to listing, even if it is not the highest-volume term.",
        "tags": ["listing photos", "seller prep", "marketplace tips", "photo checklist"],
        "links": ["selling guide posts", "contact sections", "inventory pages"],
    },
    {
        "date": "2026-06-17",
        "job_id": "2026-06-17-jma-golfcarts-common-mistakes-buying-used-golf-cart-online",
        "topic": "Common mistakes when buying a used golf cart online",
        "primary_keyword": "common mistakes buying used golf cart online",
        "secondary_keywords": [
            "avoid used golf cart buying mistakes",
            "used golf cart marketplace tips",
            "golf cart buying mistakes",
            "online golf cart buyer guide",
        ],
        "category_slug": "buying-guides",
        "category_name": "Buying Guides",
        "cluster": "buyer acquisition",
        "lead_goal": "buyer leads",
        "score": 82,
        "priority": "high",
        "word_count": 1600,
        "rationale": "Problem-avoidance content performs well for buyers early in the journey and creates natural openings for expert guidance.",
        "tags": ["buyer mistakes", "online buying", "marketplace tips", "used golf cart guide"],
        "links": ["inventory pages", "inspection posts", "contact sections"],
    },
    {
        "date": "2026-06-18",
        "job_id": "2026-06-18-jma-golfcarts-electric-vs-gas-golf-cart-for-neighborhoods",
        "topic": "Electric vs gas golf cart for neighborhoods",
        "primary_keyword": "electric vs gas golf cart for neighborhoods",
        "secondary_keywords": [
            "electric vs gas golf cart",
            "best golf cart for neighborhood streets",
            "neighborhood cart comparison",
            "golf cart fuel type guide",
        ],
        "category_slug": "brand-comparisons",
        "category_name": "Brand Comparisons",
        "cluster": "buyer acquisition",
        "lead_goal": "buyer leads",
        "score": 81,
        "priority": "medium",
        "word_count": 1600,
        "rationale": "Specific environment-based comparison content often converts better than broad electric-vs-gas articles because intent is clearer.",
        "tags": ["electric vs gas", "neighborhood carts", "comparison guide", "buyer guide"],
        "links": ["street legal posts", "inventory pages", "contact sections"],
    },
    {
        "date": "2026-06-19",
        "job_id": "2026-06-19-jma-golfcarts-what-affects-used-golf-cart-resale-value",
        "topic": "What affects used golf cart resale value",
        "primary_keyword": "what affects used golf cart resale value",
        "secondary_keywords": [
            "used golf cart value",
            "golf cart resale factors",
            "how much is used golf cart worth",
            "seller pricing guide golf cart",
        ],
        "category_slug": "selling-guides",
        "category_name": "Selling Guides",
        "cluster": "seller acquisition",
        "lead_goal": "seller leads",
        "score": 78,
        "priority": "medium",
        "word_count": 1600,
        "rationale": "Valuation-oriented seller content supports listing readiness and can convert hesitant owners into direct inquiries.",
        "tags": ["resale value", "seller pricing", "used golf cart value", "listing prep"],
        "links": ["selling guide posts", "contact sections", "inventory pages"],
    },
    {
        "date": "2026-06-22",
        "job_id": "2026-06-22-jma-golfcarts-best-4-seater-golf-cart-for-family-use",
        "topic": "Best 4 seater golf cart for family use",
        "primary_keyword": "best 4 seater golf cart for family use",
        "secondary_keywords": [
            "family golf cart buying guide",
            "best 4 passenger golf cart",
            "golf cart for neighborhood family use",
            "used 4 seater golf cart",
        ],
        "category_slug": "buying-guides",
        "category_name": "Buying Guides",
        "cluster": "buyer acquisition",
        "lead_goal": "buyer leads",
        "score": 79,
        "priority": "medium",
        "word_count": 1500,
        "rationale": "Family-use intent is commercially attractive and can create a strong bridge to inventory and comparison pages.",
        "tags": ["4 seater carts", "family use", "buyer guide", "passenger carts"],
        "links": ["inventory pages", "brand comparison posts", "contact sections"],
    },
    {
        "date": "2026-06-23",
        "job_id": "2026-06-23-jma-golfcarts-best-golf-cart-for-property-maintenance-crews",
        "topic": "Best golf cart for property maintenance crews",
        "primary_keyword": "best golf cart for property maintenance crews",
        "secondary_keywords": [
            "property maintenance golf cart",
            "utility cart for crews",
            "commercial golf cart work use",
            "maintenance fleet golf cart",
        ],
        "category_slug": "utility-work-carts",
        "category_name": "Utility & Work Carts",
        "cluster": "buyer acquisition",
        "lead_goal": "buyer leads",
        "score": 81,
        "priority": "medium",
        "word_count": 1600,
        "rationale": "Strong B2B use-case topic that supports higher-value commercial leads rather than purely recreational shoppers.",
        "tags": ["property maintenance", "utility carts", "crew vehicles", "commercial guide"],
        "links": ["inventory pages", "contact sections", "maintenance posts"],
    },
    {
        "date": "2026-06-24",
        "job_id": "2026-06-24-jma-golfcarts-how-to-compare-golf-cart-listings-online",
        "topic": "How to compare golf cart listings online",
        "primary_keyword": "how to compare golf cart listings online",
        "secondary_keywords": [
            "compare golf cart listings",
            "used golf cart marketplace comparison",
            "golf cart listing checklist",
            "evaluate golf cart listings",
        ],
        "category_slug": "buying-guides",
        "category_name": "Buying Guides",
        "cluster": "buyer acquisition",
        "lead_goal": "buyer leads",
        "score": 76,
        "priority": "medium",
        "word_count": 1500,
        "rationale": "Listing-comparison content supports marketplace trust and can move uncertain buyers toward direct help.",
        "tags": ["listing comparison", "buyer guide", "marketplace tips", "shopping checklist"],
        "links": ["inventory pages", "inspection posts", "contact sections"],
    },
    {
        "date": "2026-06-25",
        "job_id": "2026-06-25-jma-golfcarts-when-to-replace-golf-cart-batteries-before-selling",
        "topic": "When to replace golf cart batteries before selling",
        "primary_keyword": "when to replace golf cart batteries before selling",
        "secondary_keywords": [
            "replace batteries before selling golf cart",
            "sell electric golf cart with old batteries",
            "golf cart resale battery decision",
            "battery upgrade before sale",
        ],
        "category_slug": "maintenance-ownership",
        "category_name": "Maintenance & Ownership",
        "cluster": "seller acquisition",
        "lead_goal": "seller leads",
        "score": 75,
        "priority": "medium",
        "word_count": 1500,
        "rationale": "A useful seller-side ownership topic that helps convert hesitant owners who are deciding whether their cart is listing-ready.",
        "tags": ["battery replacement", "seller prep", "electric cart resale", "ownership guide"],
        "links": ["selling guide posts", "contact sections", "inventory pages"],
    },
    {
        "date": "2026-06-26",
        "job_id": "2026-06-26-jma-golfcarts-what-to-ask-before-buying-street-legal-golf-cart",
        "topic": "What to ask before buying a street legal golf cart",
        "primary_keyword": "what to ask before buying a street legal golf cart",
        "secondary_keywords": [
            "street legal golf cart buyer questions",
            "buy road legal golf cart",
            "street legal cart checklist",
            "LSV buyer guide",
        ],
        "category_slug": "street-legal-carts",
        "category_name": "Street Legal Carts",
        "cluster": "buyer acquisition",
        "lead_goal": "buyer leads",
        "score": 80,
        "priority": "medium",
        "word_count": 1600,
        "rationale": "Question-led legal/compliance content helps qualify serious buyers and supports consultative lead capture.",
        "tags": ["street legal questions", "buyer checklist", "LSV guide", "road legal carts"],
        "links": ["street legal posts", "inventory pages", "contact sections"],
    },
    {
        "date": "2026-06-29",
        "job_id": "2026-06-29-jma-golfcarts-how-dealers-can-move-used-golf-cart-inventory-faster",
        "topic": "How dealers can move used golf cart inventory faster",
        "primary_keyword": "how dealers can move used golf cart inventory faster",
        "secondary_keywords": [
            "dealer golf cart inventory strategy",
            "move used golf carts faster",
            "golf cart dealer resale tips",
            "marketplace strategy for dealers",
        ],
        "category_slug": "selling-guides",
        "category_name": "Selling Guides",
        "cluster": "seller acquisition",
        "lead_goal": "dealer leads",
        "score": 83,
        "priority": "high",
        "word_count": 1700,
        "rationale": "Dealer-facing content can create fewer but stronger lead opportunities and aligns closely with marketplace monetization goals.",
        "tags": ["dealer strategy", "inventory turnover", "seller guide", "marketplace tips"],
        "links": ["contact sections", "inventory pages", "selling guide posts"],
    },
    {
        "date": "2026-06-30",
        "job_id": "2026-06-30-jma-golfcarts-golf-cart-charger-problems-buyers-should-check-first",
        "topic": "Golf cart charger problems buyers should check first",
        "primary_keyword": "golf cart charger problems buyers should check first",
        "secondary_keywords": [
            "used golf cart charger issues",
            "buyer checklist charger",
            "electric golf cart charger problems",
            "golf cart ownership guide",
        ],
        "category_slug": "maintenance-ownership",
        "category_name": "Maintenance & Ownership",
        "cluster": "ownership education",
        "lead_goal": "buyer leads",
        "score": 74,
        "priority": "medium",
        "word_count": 1500,
        "rationale": "A practical quality-filter topic that helps buyers avoid problem listings and builds trust in the site’s guidance.",
        "tags": ["charger problems", "buyer checklist", "electric cart guide", "ownership tips"],
        "links": ["buying guide posts", "inventory pages", "contact sections"],
    },
]


def build_job(plan: dict, site_id: str, planned_date: str) -> dict:
    slug = slugify(plan["topic"])
    return {
        "job_id": plan["job_id"],
        "site_id": site_id,
        "topic": plan["topic"],
        "primary_keyword": plan["primary_keyword"],
        "secondary_keywords": plan["secondary_keywords"],
        "target_url": f"/blog/{plan['category_slug']}/{slug}",
        "status": "new",
        "priority": plan["priority"],
        "assigned_reviewer": REVIEWER,
        "created_at": CREATED_AT,
        "updated_at": UPDATED_AT,
        "planned_publish_date": planned_date,
        "calendar_month": CALENDAR_LABEL,
        "seo_strategy": {
            "search_intent": "commercial informational",
            "cluster": plan["cluster"],
            "lead_goal": plan["lead_goal"],
            "opportunity_score": plan["score"],
            "opportunity_rationale": plan["rationale"],
            "category_slug": plan["category_slug"],
            "category_name": plan["category_name"],
            "suggested_tags": plan["tags"],
            "recommended_internal_link_types": plan["links"],
        },
        "metrics": {
            "target_word_count": plan["word_count"],
            "neuronwriter_score": None,
            "manual_plagiarism_status": "Pending manual review",
        },
        "publish": {
            "commit_sha": None,
            "live_url": None,
        },
    }


def job_filename(plan: dict) -> str:
    return f"{plan['job_id']}.json"


def update_or_create_jobs(plans: list[dict], site_id: str) -> None:
    scheduled_dates = next_workdays(START_DATE, len(plans))
    for index, plan in enumerate(plans):
        path = JOBS_DIR / job_filename(plan)
        payload = build_job(plan, site_id, scheduled_dates[index])
        if path.exists():
            current = json.loads(path.read_text())
            current.update(
                {
                    "topic": payload["topic"],
                    "primary_keyword": payload["primary_keyword"],
                    "secondary_keywords": payload["secondary_keywords"],
                    "target_url": payload["target_url"],
                    "priority": payload["priority"],
                    "planned_publish_date": payload["planned_publish_date"],
                    "calendar_month": payload["calendar_month"],
                }
            )
            current.setdefault("seo_strategy", {})
            current["seo_strategy"].update(payload["seo_strategy"])
            current.setdefault("metrics", {})
            current["metrics"]["target_word_count"] = payload["metrics"]["target_word_count"]
            current["metrics"].setdefault("neuronwriter_score", None)
            current["metrics"].setdefault("manual_plagiarism_status", "Pending manual review")
            current["updated_at"] = UPDATED_AT
            path.write_text(json.dumps(current, indent=2) + "\n")
        else:
            path.write_text(json.dumps(payload, indent=2) + "\n")


def write_markdown_calendar() -> None:
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    crane_dates = next_workdays(START_DATE, len(CRANES))
    jma_dates = next_workdays(START_DATE, len(JMA))
    lines = [
        "# Rolling Working-Day Content Calendar",
        "",
        "Assumptions:",
        "- Working days only means Monday to Friday.",
        "- Schedule starts from the next working day after setup (`2026-05-20`).",
        "- Calendar span: late May through mid June 2026 (`22` working days).",
        "- Goal: one lead-oriented blog per working day for each site.",
        "- Brand rule: use `Jeff Martin Auctioneers` or generic language in conversion copy, never the microsite as the speaking brand.",
        "",
        "## CranesAuctions",
        "",
        "| Date | Category | Topic | Primary keyword | Lead goal | Score |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for item, planned_date in zip(CRANES, crane_dates):
        lines.append(
            f"| {planned_date} | {item['category_name']} | {item['topic']} | `{item['primary_keyword']}` | {item['lead_goal']} | {item['score']} |"
        )

    lines.extend(
        [
            "",
            "## JMA Golf Carts",
            "",
            "| Date | Category | Topic | Primary keyword | Lead goal | Score |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
    )
    for item, planned_date in zip(JMA, jma_dates):
        lines.append(
            f"| {planned_date} | {item['category_name']} | {item['topic']} | `{item['primary_keyword']}` | {item['lead_goal']} | {item['score']} |"
        )

    (DOCS_DIR / "2026-05-to-06-working-days.md").write_text("\n".join(lines) + "\n")


def main() -> None:
    update_or_create_jobs(CRANES, "cranes-auctions")
    update_or_create_jobs(JMA, "jma-golfcarts")
    write_markdown_calendar()
    print(f"Seeded {len(CRANES)} CranesAuctions jobs and {len(JMA)} JMA Golf Carts jobs.")


if __name__ == "__main__":
    main()
